Swisscom:
  CommunicationDispatcher:
    dispatcherConfigurations:
      emailChannel:
        objectName: '\Swisscom\CommunicationDispatcher\Dispatcher\Dispatcher'
        channelObjectName: '\Swisscom\CommunicationDispatcher\Channel\EmailChannel'
        channelOptions: []
      notificationChannel:
        objectName: '\Swisscom\CommunicationDispatcher\Dispatcher\Dispatcher'
        channelObjectName: '\Swisscom\CommunicationDispatcher\Channel\NotificationChannel'
        channelOptions: []
    renderingErrorMessage: 'Template rendering failed'
    subjectPrefix: ''
    partialRootPath: null
    templateSourceNamespaces: []
    templateViewStaticParameters: []

    log:
      logger:
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/CommunicationDispatcher.log'
          createParentDirectories: TRUE
          severityThreshold: '%LOG_INFO%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logIpAddress: TRUE